sudo: false
language: go
git:
    depth: 1
install: go get -v github.com/spf13/hugo
script: hugo
deploy:
    provider: pages
    skip_cleanup: true
    github_token: 6eaa92753dff40e54d97ef726f236f0f988f597d
    on:
        branch: master
    local_dir: public
    repo: dreamsfuture/dreamsfuture.github.io
    fqdn: <custom-domain-if-needed>
    target_branch: master
    email: dreamsfuture@qq.com
    name: dreamsfuture