baseURL = "https://dreamsfuture.github.io"
languageCode = "zh-CN"
defaultContentLanguage = "zh"

title = "Dreamsfuture"

theme = "dream_theme"
googleAnalytics = "GA ID"  # UA-XXXXXXXX-X

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 140

disqusShortname = "dreamsfuture"  ## 是否开启disqus评论，不要和utteranc同时开启


copyright = "Copyright All Reserved."


enableRobotsTXT = true



[params]
  backgroundImage = "img/background.jpg"
  author = " Dreamsfuture"
  rss = true
  
  googleAd = "ca-pub-4031353640611810"  #ca-pub-xxxxxxxxxxxxxx
  localSearch = true # 启用本地搜索
  motto = "If one thing was done by one person, it can be done by others!"
  siteStartYear = 2016

  avatar = "/img/avatar.jpg"
  favicon = "img/favicon.ico"

  email = "dreamsfuture@buaa.edu.cn"
  baidu = "www.baidu.com"
  twitter = ""
  facebook = ""
  instagram = ""
  linkedin = ""
  github = "dreamsfuture"

  stackoverflow = ""
  codepen = ""

  # options
  showSummaryCoverInPost = true

  # dark mode
  # darkLinkColor = "darkseagreen"
  # darkNav = true 
  # dark404 = true

  # utterancesRepo = ""


  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = true  # 是否开启目录
